### ISSUE TITLE
Produce file view by percentage of students in the last X weeks

### ISSUE THREAD

**Issue by zqian** [tl-its-umich-edu/student-dashboard-django#14]
Need to generate a similar view of file viewing patterns as demoed in this [Tableau view.](https://tableau.dsc.umich.edu/#/site/UM/views/Aug1-Fileleaderboard-STATS250SP18/Dashboard1?:iid=1)

**Comment by kaaaka1995** [comment]
Tableau visualization: https://tableau.dsc.umich.edu/#/site/UM/views/Aug9-Fileleaderboard-STATS250SP18/Dashboard1?:iid=1
