### ISSUE TITLE
Files view page: Show the drop-down by ranking rather than A, B, C

### ISSUE THREAD

**Issue by kaaaka1995** [tl-its-umich-edu/student-dashboard-django#140]
Show the drop-down by ranking rather than A, B, C
Instead of grades show students with 90-100%, students with 80-89%, students with 70-79%

**Comment by zqian** [comment]
Done.

**Comment by jonespm** [comment]
@zqian Did you intend to reopen this?

**Comment by jonespm** [comment]
Guessing not, looks like this was fixed in #157
