### ISSUE TITLE
duplicate records in the databases table when running the testLoader

### ISSUE THREAD

**Issue by pushyamig** [tl-its-umich-edu/student-dashboard-django#162]

**Comment by jonespm** [comment]
Probably is related to this if_exists='append'. We probably will need to change these to replace? 

```
if_exists : {‘fail’, ‘replace’, ‘append’}, default ‘fail’

How to behave if the table already exists.

fail: Raise a ValueError.
replace: Drop the table before inserting new values.
append: Insert new values to the existing table.
```

Though I wonder if we'll need a better pattern for the creation of these tables? 

I also wonder if having index=False isn't causing performance problems that @zqian is seeing? We should always have one column that's an index.

**Comment by pushyamig** [comment]
A good test case from 
1. the Grades view `Total # of students == Number of students in the class1. for course `[252306:208,245664:37,283292:69]`
2. Assignment view should not show duplicate assignment in the tabular/ progress view

**Comment by jonespm** [comment]
This should be resolved after the recent cronjob changes.
