### ISSUE TITLE
Change wording for drop-down on What Students Are Reading page

### ISSUE THREAD

**Issue by jennlove-um** [tl-its-umich-edu/student-dashboard-django#178]
New wording: 

Files accessed by students with a grade of _________ from Week....

**Comment by jennlove-um** [comment]
We can run this wording by the group on Thursday.  It doesn't exactly fit with the "All" option, but works for  the others.

**Comment by zqian** [comment]
Jennifer, based on the Thursday discussion, Matt created a new request: [issue_195](https://github.com/tl-its-umich-edu/student-dashboard-django/issues/195)
So maybe we can close this one instead?

**Comment by jennlove-um** [comment]
Yes, this was my initial draft of wording.  But what we decided on Thursday means this issue is no longer relevant.
