### ISSUE TITLE
Change link on Canvas Files page to match the name of the page on the Dashboard

### ISSUE THREAD

**Issue by jennlove-um** [tl-its-umich-edu/student-dashboard-django#179]
The link on the Canvas Files page needs to use the same name as the files visualization page on the dashboard.

Text should be "What Students are Reading"

**Comment by jennlove-um** [comment]
We can review the page title again in the meeting this week.  This issue is to make sure we make the link match the page title.

**Comment by zqian** [comment]
This is no longer an issue with the new home page.

**Comment by jennlove-um** [comment]
Retested - link today has the correct text and icon in Canvas test.
