### ISSUE TITLE
Write Help documentation for the Student Dashboard

### ISSUE THREAD

**Issue by jennlove-um** [tl-its-umich-edu/student-dashboard-django#183]
Write a help as a Google site for the help: https://sites.google.com/umich.edu/student-dashboard-help/home

**Comment by pushyamig** [comment]
The effort is checked into the master, and should be ready for testing. If URL changes for some reason I will work through the changes again

**Comment by jennlove-um** [comment]
Testing passes in dev.  Clicking help at the top of each page opens the correct help page in a new window.
