### ISSUE TITLE
Assignment Planning changes based on feedback 2018/10/04

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/student-dashboard-django#194]
Raise the Current and Max Possible up above the bar to show a little white space
Make them bold instead of using a stroke-width
Make the title column wider since there is space on the screen
Titles are bleeding into the 
Scale the Percent of final grade to use less space
Left-align all of the columns, title and content
Change “Due Date” to “Due”

**Comment by pushyamig** [comment]
Done.

**Comment by jennlove-um** [comment]
One quick fix - the title on the due date column should be "Due" (not "Date") per meeting notes.
