### ISSUE TITLE
Change Header Title to Remove the Phrase "Dashboard"

### ISSUE THREAD

**Issue by johnpj** [tl-its-umich-edu/student-dashboard-django#199]
Using the phrase "Dashboard" is antithetical to the whole philosophy we've been working against in the unDashboard development. Jen Love and Zhen have agreed on "My Learning Analytics. " It fits with the naming conventions in Canvas where assignments are Assignments and discussions are Discussions.

**Comment by jonespm** [comment]
There are more references to "dashboard" than this. Rebranding would be a little effort at this point.

- Changing the domain name requires work across multiple groups to get a new domain (About a day), New SSL certs (About a day) and adding Shibboleth support (Up to a week)

-We'd also want to rename the project in github. This should keep old things working but not something we want to do frequently.

What should the names be if we are changing domain names. "My Learning Analytics" is too long. MLA has some brand confusion with "Modern Language Association".

We can keep both domains active but I think the next move should be the last for awhile.

**Comment by johnpj** [comment]
I don't think we need to change the domain at this point; especially considering the users will be launching the tools from Canvas.
