### ISSUE TITLE
Fix Help Link

### ISSUE THREAD

**Issue by johnpj** [tl-its-umich-edu/student-dashboard-django#217]
The Help link is pointing to the old URL which no longer exists. The correct URL is: 
https://sites.google.com/umich.edu/my-learning-analytics-help/home

**Comment by jennlove-um** [comment]
There are more broken help links as a result of changing names to match the new analytics names: 

Help link on the Files page: https://sites.google.com/umich.edu/my-learning-analytics-help/home/files-accessed

Help link on the Assignments page: https://sites.google.com/umich.edu/my-learning-analytics-help/home/assignment-planning

Could you update these as well?

**Comment by jennlove-um** [comment]
Tested in dev and production.  Links correctly go to the renamed help pages.
