### ISSUE TITLE
Do not allow SI 110 pilot course to access Grade Distribution view

### ISSUE THREAD

**Issue by jennlove-um** [tl-its-umich-edu/student-dashboard-django#229]
The instructor for SI 110 does not want his students using the Grade Distribution view.

We won't put a link to Grade Distribution on the Canvas Grades page.

We need to have a way to prevent students in 252307 from seeing the Grade Distribution page or at least from seeing any data on that page.

**Comment by jonespm** [comment]
Should this view be course by course "opt-in" or an "opt-out"? We could hard-code the list of Canvas ID's but just like the cron loader should come up with a better future process.

**Comment by jennlove-um** [comment]
For the pilot, we can go with a hard-code option, I think.  

I agree that for the future this is a larger question of what should be configurable by the instructors for their course(s) and how to build that in.

**Comment by jonespm** [comment]
Yeah I'm thinking minimally we'll want a database table that's something like

- canvas_course_id
- show_grades
- show_assignments
- show_files

Then we (admins) can manipulate this easily in the admin interface. 

Another thing I was thinking about with this is I "believe" instructors are going to be blocked from the course once we enable authentication. Obviously instructors won't have as much useful data but I don't think we're considering the instructor case at all right?

**Comment by jennlove-um** [comment]
I think instructors will be curious to see what their students are seeing.  They may be especially invested in seeing what Files are being viewed.

**Comment by zqian** [comment]
I will go with the database approach.

**Comment by zqian** [comment]
No good solution for instructor view as of now.

**Comment by pushyamig** [comment]
if the DB route turns out too much before tomorrow then we can disable the link on the home page 
```
if( course == 252307){
no grades link
}
```

based on the help documantation if students did figure out grades URL then
in the `views.py` we can add a check
```
if(course== 252307){
     HttpResponse(json.dumps({}), content_type='application/json')
} 
```
Currently UI handles it with message  " No data for the view"

**Comment by jonespm** [comment]
Yeah, we also could have the cron just not populate the current_grade for students in that course right? Then it will just display a no data link. 

Maybe that message could be clearer? "Either you have no data or your instructor has disabled this view"

**Comment by pushyamig** [comment]
I think files view is using the grades data as drop-down has % grade populating it so we cannot remove it totally

**Comment by jonespm** [comment]
This is fixed
