### ISSUE TITLE
Change the Assignment Design that it is not closely tied to the student information

### ISSUE THREAD

**Issue by pushyamig** [tl-its-umich-edu/student-dashboard-django#245]
This is mostly due to the way the DB query made closely w.r.t to Student data.  The view should show course data irrespective for admins and only course specific instructor

**Comment by pushyamig** [comment]
Test Plan: 
Logging as admin/or any student that are not part of the course should be able to see the Non-personalized view. 

I won't see this is a ideal design for showing other who are not part of the course to see course related information but that what other 2 views are supporting now. That would be a separate issue to fix showing the content specific to the user

**Comment by jennlove-um** [comment]
Testing passes.  The non-personalized view shows for the admin or for a student who is not in the course selected.  The personalized view shows for a student in the course (SI 110 tested).
