### ISSUE TITLE
Multiple students in different courses is not handled currently

### ISSUE THREAD

**Issue by pushyamig** [tl-its-umich-edu/student-dashboard-django#248]
The pilot courses don't seems to have students in multiple courses but the `user` table that is created as such  you cannot add a same user with different course. `User` table PK needs to be based of `user_id and course_id`.

**Comment by pushyamig** [comment]
Test Plan: This changes Primary Key(PK) for the user table. Making a new column as PK should not impact the views at all

1. Make sure Files/assignment/grades personalized and non-personalized view is loading correctly.
Testing this is more or less like a regression testing.

**Comment by jennlove-um** [comment]
As far as I can tell this is working.  I see the correct view of the screens when I'm logged in as myself (non-personalized) and when I masquerade as a student in SI 110. 

The only view I can't test is the grade distribution view - we don't have a student from the SI 664 or HMP 654 to test with in dev.
