### ISSUE TITLE
Fix the issue where muted grades are visible to students

### ISSUE THREAD

**Issue by pushyamig** [tl-its-umich-edu/student-dashboard-django#251]

**Comment by pushyamig** [comment]
Test Plan: The course that is using this Muting the assignment approach is SI 100 and other 2 pilot course doesn't seems to be doing this i.e Muted is False by default.
1. See if all the assignment that are visible to student are also visible in Dashboard
2. Students only should see grades that are visible for them. Go to the student view of the student and get the list of grades they can see map them with stud_dash. if there are more grades in the canvas view that are showed and not seen from stu_dash this would be because UDW don't have those grades yet.
3. Pick an assignment that is currently muted and the grades should not be visible to student.

**Comment by jennlove-um** [comment]
Testing passes

1. All assignments that the student can see in the Canvas course are displayed in both the progress bar and the assignment list.

2. Grades that display in the dashboard are the same grades that display to the student.

3. Assignments that are muted do not display grades to students.  This is true if the assignment have been graded or ungraded.
