### ISSUE TITLE
Switch from bower to yarn, npm (or something else)

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/student-dashboard-django#27]
Bower is deprecated and since this project is relatively new we should switch before too much work gets put into bower. (Really not that much at the moment)

https://bower.io/blog/2017/how-to-migrate-away-from-bower/

**Comment by lsloan** [comment]
But they had such a cool logo! 😉

Seriously, though, it's interesting that they don't actually use the word "deprecated" WRT Bower.
