### ISSUE TITLE
provide "become user" functionality for admin/instructor users

### ISSUE THREAD

**Issue by zqian** [tl-its-umich-edu/student-dashboard-django#35]
Related to issue_34, we need a way to override the shibboleth user and give admin/instructor users the ability to "become user". We can add those users to certain MComm group for better account management.

**Comment by jonespm** [comment]
I feel like the process of changing the user will be easy. We'll have to flowchart how the process to make it work easier will look like though.

My guess is that there would have to be some page that would get the users courses where they are an instructor, user would select a course and select a student and select to become this student. 

It would have to re-verify that this instructor can become this student before switching and switch over. Then either "logout" and re-login to the SAML credentials, or "logout" back to the original credentials.
