### ISSUE TITLE
Add a Google Analytics plugin for Dashboard tool pages

### ISSUE THREAD

**Issue by zqian** [tl-its-umich-edu/student-dashboard-django#52]
We will use the following tracking id to track the usage of Student Dashboard usage:

<script async src="https://www.googletagmanager.com/gtag/js?id=UA-124181744-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-124181744-1');
</script>

**Comment by kaaaka1995** [comment]
https://github.com/tl-its-umich-edu/student-dashboard-django/wiki/Student-dashboard-project-test-plan

**Comment by jonespm** [comment]
This should have been resolved by #74

**Comment by jonespm** [comment]
@kaaaka1995 Maybe you want to reverify?
