### ISSUE TITLE
a couple of changes needed for the file access view

### ISSUE THREAD

**Issue by zqian** [tl-its-umich-edu/student-dashboard-django#72]
During the 09/06 project meeting, a couple of issues were raised:

- make the file title as a clickable link
- put a title for page as "What Students Are Reading?"
- combine the week number with Grade drop-down list as one status line
- make the color consistent in the minor sliding bar

**Comment by jonespm** [comment]
Were you working on this or did you want to assign some/all of this to me?

**Comment by zqian** [comment]
this is done.

**Comment by jonespm** [comment]
Fixed in #73
